\input texinfo

@c This file is part of ljupdate, a LiveJournal client for Emacs.

@c ljupdate is free software; you can redistribute it and/or modify it
@c under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2, or {at your option}
@c any later version.

@c ljupdate is distributed in the hope that it will be useful, but
@c WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
@c General Public License for more details.

@c You should have received a copy of the GNU General Public License
@c along with GNU Emacs; see the file COPYING, or type `C-h C-c'. If
@c not, write to the Free Software Foundation at this address:

@c     Free Software Foundation
@c     51 Franklin Street, Fifth Floor
@c     Boston, MA 02110-1301
@c     USA

@setfilename ljupdate.info
@settitle ljupdate: an Emacs LiveJournal client

@dircategory Emacs
@direntry
* ljupdate: (ljupdate).	an Emacs LiveJournal client.
@end direntry

@node           Top, Internals,    (dir), (dir)
@comment  node-name,      next, previous,    up
@top ljupdate: an Emacs LiveJournal client

ljupdate is an Emacs client for the LiveJournal blogging system.

@menu
* Internals::           How ljupdate is architected
@end menu

@node     Internals, Bleah,      Top, Top
@comment  node-name,  next, previous,  up
@chapter Internals

bleah bleah bleah.

